#Kabanero! on activate substitute CollectionId for text 'CollectionId'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: CollectionId-build-deploy-pl
spec:
  params:
  - name: event-headers
    type: string
    description: "The event headers"
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-deploy-task
    taskRef:
      name: CollectionId-build-deploy-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
  - name: image-scan-task
    taskRef:
      name: CollectionId-image-scan-task
    runAfter: [build-deploy-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
